package br.com.dmcconsulting.designsystem.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFb71b3f)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFffdadb)
val md_theme_light_onPrimaryContainer = Color(0xFF40000E)
val md_theme_light_secondary = Color(0xFF765658)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFffdadb)
val md_theme_light_onSecondaryContainer = Color(0xFF2c1517)
val md_theme_light_tertiary = Color(0xFF775930)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFffddb4)
val md_theme_light_onTertiaryContainer = Color(0xFF291800)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFffdad6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFfffbff)
val md_theme_light_onBackground = Color(0xFF201a1a)
val md_theme_light_surface = Color(0xFFfffbff)
val md_theme_light_onSurface = Color(0xFF201a1a)
val md_theme_light_surfaceVariant = Color(0xFFf4ddde)
val md_theme_light_onSurfaceVariant = Color(0xFF524344)
val md_theme_light_outline = Color(0xFF857373)
val md_theme_light_inverseOnSurface = Color(0xFFFFECF0)
val md_theme_light_inverseSurface = Color(0xFF5D1137)
val md_theme_light_inversePrimary = Color(0xFFFFB2B8)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFB71B3F)
val md_theme_light_outlineVariant = Color(0xFFD7C1C2)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFffb2b8)
val md_theme_dark_onPrimary = Color(0xFF67001c)
val md_theme_dark_primaryContainer = Color(0xFF91002c)
val md_theme_dark_onPrimaryContainer = Color(0xFFffdadb)
val md_theme_dark_secondary = Color(0xFFe6bdbe)
val md_theme_dark_onSecondary = Color(0xFF44292b)
val md_theme_dark_secondaryContainer = Color(0xFF5c3f41)
val md_theme_dark_onSecondaryContainer = Color(0xFFffdadb)
val md_theme_dark_tertiary = Color(0xFFe7c08e)
val md_theme_dark_onTertiary = Color(0xFF432c06)
val md_theme_dark_tertiaryContainer = Color(0xFF5d421b)
val md_theme_dark_onTertiaryContainer = Color(0xFFffddb4)
val md_theme_dark_error = Color(0xFFffb4ab)
val md_theme_dark_errorContainer = Color(0xFF93000a)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFffdad6)
val md_theme_dark_background = Color(0xFF201a1a)
val md_theme_dark_onBackground = Color(0xFFece0df)
val md_theme_dark_surface = Color(0xFF201a1a)
val md_theme_dark_onSurface = Color(0xFFece0df)
val md_theme_dark_surfaceVariant = Color(0xFF524344)
val md_theme_dark_onSurfaceVariant = Color(0xFFd7c1c2)
val md_theme_dark_outline = Color(0xFF9f8c8d)
val md_theme_dark_inverseOnSurface = Color(0xFF3E0021)
val md_theme_dark_inverseSurface = Color(0xFFFFD9E4)
val md_theme_dark_inversePrimary = Color(0xFFB71B3F)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB2B8)
val md_theme_dark_outlineVariant = Color(0xFF524344)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFCA2B4B)
